### PR TITLE
feat: Disable Raven logging based on env var ✨

### LINKED ISSUE #85: Self hosted version
Is it possible to deploy this to a self-hosted service? The source code kind of assumes public GitHub for URLs and stuff so it doesn't seem possible at the moment but it'd be cool if it did support that.

### PR DESCRIPTION
**Pull request by mrchief**
Partially fixes #85

### CODE REVIEW

**Comment by mrchief** [comment]
@ewolfe Looks like the tests failed because `PRIVATE_KEY_B64` is not set somehow? Not sure what's missing.

**Comment by mrchief** [comment]
Verified locally that all tests pass by providing a fake `PRIVATE_KEY_B64` via a local `.env` file. Looks like we need to change the CI setup to pass this for all builds?

**Comment by ewolfe** [comment]
Hey @mrchief I'm awfully swamped at work right now and won't be able to look at this in a timely manner. I'm going to add you to this repo and travis-ci so you make any needed changes :)

**Review by ewolfe — APPROVED** [review]
Pending the travis-ci config needing to get fixed, this looks okay

**Comment by ewolfe** [comment]
PS I added you as a collaborator to the repo, I _think_ this will give you access to travis-ci. You might need to just edit/update the travis-ci config file. If you think you might need to fiddle with any of the environment variables, please ping me first!

**Caution area:**
image

**Comment by mrchief** [comment]
> PS I added you as a collaborator to the repo, I think this will give you access to travis-ci. 

Yep it does. Thanks for the consideration.

> You might need to just edit/update the travis-ci config file. If you think you might need to fiddle with any of the environment variables, please ping me first!

I probably won't need that if I close my fork's branch and move my changes to a branch in this repo. If that works, I won't need to tinker with anything.

**Pull request closed without merging**
